name: Daily News Digest

on:
  schedule:
    # Run daily at 9:00 AM Eastern Time (UTC-5, so 14:00 UTC)
    - cron: '0 14 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  news-digest:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create environment file
      run: |
        cat > .env << EOF
        NEWSAPI_KEY=${{ secrets.NEWSAPI_KEY }}
        GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
        EMAIL_SENDER=${{ secrets.EMAIL_SENDER }}
        EMAIL_RECIPIENTS=${{ secrets.EMAIL_RECIPIENTS }}
        EOF
        
    - name: Create Gmail credentials
      run: |
        echo '${{ secrets.CREDENTIALS_JSON_B64 }}' | base64 -d > credentials.json
        
    - name: Create Gmail token (if exists)
      run: |
        if [ -n "${{ secrets.TOKEN_JSON_B64 }}" ]; then
          echo '${{ secrets.TOKEN_JSON_B64 }}' | base64 -d > token.json
        fi
        
    - name: Run daily news digest
      run: python main.py
      
    - name: Upload email preview as artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: email-preview
        path: email_preview.html
        retention-days: 7 